---
apiVersion: v1
kind: Service
metadata:
  name: crime-map-backend
spec:
  selector:
    app: crime-map-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http