apiVersion: apps/v1
kind: Deployment
metadata:
  name: crime-map-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crime-map-backend
  template:
    metadata:
      labels:
        app: crime-map-backend
    spec:
      containers:
        - name: crime-map-backend
          image: g1ymoore/crime-map:crime-map-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: apple-maps-credentials
              mountPath: "/usr/share/crime-map/secrets"
          env:
            - name: "FLASK_ENV"
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /entries?days=1
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: apple-maps-credentials
          secret:
            secretName: apple-maps-key
            items:
              - key: private-key
                path: private-key
                mode: 511
              - key: issuer-id
                path: issuer-id
                mode: 511
              - key: key-id
                path: key-id
                mode: 511
---
apiVersion: v1
kind: Service
metadata:
  name: crime-map
  namespace: crime-map
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http2"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "e1ed8f63-4e8c-476b-8d03-85328de244e7"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  selector:
    app: crime-map-backend
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: crime-map-backend
  namespace: crime-map
spec:
  selector:
    app: crime-map-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http
