---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    name: kafka-cluster
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-broker
    id: "0"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  template:
    metadata:
      labels:
        app: kafka-broker
        id: "0"
    spec:
      containers:
      - name: kafka-broker
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30718"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-cluster
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
