apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: crime-map
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "mongo"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: do-block-storage
